# Generated by Django 4.2.3 on 2023-09-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TV', 'Television'), ('AU', 'Audio'), ('AC', 'Air conditioner'), ('TV', 'Homeware'), ('CM', 'Cameras'), ('AU', 'Refrigerators'), ('GC', 'Gas cookers'), ('FZ', 'Freezers'), ('WM', 'Washing machine'), ('FN', 'Fans'), ('KA', 'Kitchen Appliances')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
